add lab3
nipoks/OC pull request #1
Opened 2023-12-20 11:25 UTC by nipoks

2023-12-24 14:24 UTC, k-stolyarov requested changes
Please share performance testing results on small/average/big structures and compare to "cp-r" command. You need to define what is small/moderate/average by yourself :)

2023-12-24 14:24 UTC, k-stolyarov commented on lab3.c
> +    if (src_fd < 0) {
![Uploading image.png…]()

2023-12-24 14:24 UTC, k-stolyarov commented on lab3.c
> +    pthread_t threadArr[1024]; //Ограниченное количество файлов в директории
If you have limited arrays please handle access to it's elements to avoid buffer overflows.

2024-01-04 13:44 UTC, nipoks commented on lab3.c
> +    pthread_t threadArr[1024]; //Ограниченное количество файлов в директории
В while добавлена проверка

2024-01-04 15:47 UTC, k-stolyarov approved these changes
Accepted

2024-09-16 12:51 UTC, merged